# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gabrielle
tagline:          'a web developer'
description:      'dream chaser by day, day dreamer by night'
url:              https://twitter.com/gabydi106
baseurl:          /

author:
  name:           'Gaby Di'
  url:            https://twitter.com/gabydi106

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
